export type Permission =

  // ===== MENU =====
  | 'P_MENU_VIEW_MODULE'

  | 'P_MENU_CREATE' | 'P_MENU_LIST_VIEW'

  | 'P_MENU_DETAILS_VIEW' | 'P_MENU_MODIFY' | 'P_MENU_DELETE' | 'P_MENU_FOOD_CREATE'
  | 'P_MENU_FOOD_DETAILS_VIEW' | 'P_MENU_FOOD_MODIFY' | 'P_MENU_FOOD_DELETE'

  // ===== ORDERS =====
  | 'P_ORDER_VIEW_MODULE'

  | 'P_ORDER_LIST_VIEW'

  | 'P_ORDER_DETAILS_VIEW' | 'P_ORDER_ADVANCE_ACCEPT' | 'P_ORDER_ADVANCE_PREPARE'
  | 'P_ORDER_ADVANCE_SERVE'

  // ===== WORKER =====
  | 'P_WORKER_VIEW_MODULE'

  | 'P_WORKER_LIST_VIEW' | 'P_WORKER_CREATE' | 'P_WORKER_RESOLVE_DAY_OFF_REQUEST'

  | 'P_WORKER_DETAILS_VIEW' | 'P_WORKER_PASSWORD_RESET' | 'P_WORKER_PASSWORD_CHANGE'
  |  'P_WORKER_PERMISSIONS_EDIT'

  // ===== SUPPLY =====
  | 'P_SUPPLY_VIEW_MODULE'

  | 'P_SUPPLY_LIST_VIEW' | 'P_SUPPLY_CREATE'

  | 'P_SUPPLY_DETAILS_VIEW' | 'P_SUPPLY_REQUEST_ACCEPT' | 'P_SUPPLY_REQUEST_ADVANCE'
  | 'P_SUPPLY_REQUEST_CANCEL';

export const ALL_PERMISSIONS: Permission[] = ['P_MENU_VIEW_MODULE', 'P_MENU_CREATE', 'P_MENU_LIST_VIEW', 'P_MENU_DETAILS_VIEW',
  'P_MENU_MODIFY', 'P_MENU_DELETE', 'P_MENU_FOOD_CREATE', 'P_MENU_FOOD_DETAILS_VIEW', 'P_MENU_FOOD_MODIFY', 'P_MENU_FOOD_DELETE',
  'P_ORDER_VIEW_MODULE', 'P_ORDER_LIST_VIEW', 'P_ORDER_DETAILS_VIEW', 'P_ORDER_ADVANCE_ACCEPT', 'P_ORDER_ADVANCE_PREPARE',
  'P_ORDER_ADVANCE_SERVE', 'P_WORKER_VIEW_MODULE', 'P_WORKER_LIST_VIEW', 'P_WORKER_CREATE', 'P_WORKER_RESOLVE_DAY_OFF_REQUEST',
  'P_WORKER_DETAILS_VIEW', 'P_WORKER_PASSWORD_RESET', 'P_WORKER_PASSWORD_CHANGE', 'P_WORKER_PERMISSIONS_EDIT', 'P_SUPPLY_VIEW_MODULE',
  'P_SUPPLY_LIST_VIEW', 'P_SUPPLY_CREATE', 'P_SUPPLY_DETAILS_VIEW', 'P_SUPPLY_REQUEST_ACCEPT', 'P_SUPPLY_REQUEST_ADVANCE',
  'P_SUPPLY_REQUEST_CANCEL'];
